export const DEFAULTS = {
  enabled: true,
  mode: "reject", // reject | hide | accept
  blockCmpScripts: true,
  blockTrackers: true,
  stripTrackingCookies: true,
  whitelist: [],
  stats: {
    banners: 0,
    clicks: 0,
    hides: 0,
    trackers: 0,
    cookies: 0
  }
};

/** Domains whose cookies we purge aggressively (trackers only — not login sites). */
export const TRACKER_COOKIE_DOMAINS = [
  "doubleclick.net",
  "google-analytics.com",
  "googletagmanager.com",
  "googlesyndication.com",
  "googleadservices.com",
  "facebook.net",
  "scorecardresearch.com",
  "quantserve.com",
  "hotjar.com",
  "adsrvr.org",
  "adnxs.com",
  "criteo.com",
  "criteo.net",
  "rubiconproject.com",
  "pubmatic.com",
  "casalemedia.com",
  "demdex.net",
  "everesttech.net",
  "amazon-adsystem.com",
  "clarity.ms",
  "taboola.com",
  "outbrain.com",
  "segment.io",
  "mixpanel.com",
  "amplitude.com",
  "fullstory.com",
  "ads-twitter.com",
  "nr-data.net",
  "newrelic.com",
  "liadm.com",
  "rlcdn.com",
  "bluekai.com",
  "exelator.com",
  "krxd.net",
  "mathtag.com",
  "moatads.com",
  "mookie1.com",
  "adform.net",
  "liveramp.com",
  "sharethis.com",
  "addthis.com",
  "indexww.com",
  "eyeota.net",
  "33across.com",
  "tribalfusion.com",
  "simpli.fi",
  "bidswitch.net",
  "ipredictive.com",
  "adsymptotic.com",
  "mouseflow.com",
  "crazyegg.com",
  "luckyorange.com",
  "branch.io",
  "app.link",
  "adjust.com",
  "appsflyer.com",
  "kochava.com",
  "chartbeat.com",
  "parsely.com",
  "comscore.com",
  "contextweb.com",
  "smartadserver.com",
  "teads.tv",
  "yieldmo.com",
  "3lift.com",
  "sharethrough.com",
  "sonobi.com",
  "spotx.tv",
  "yieldlab.net"
];

/** First-party cookie names that are almost always trackers. */
export const TRACKING_COOKIE_NAMES = [
  "_ga",
  "_gid",
  "_gat",
  "_gcl_au",
  "_gcl_aw",
  "_gcl_dc",
  "_gat_gtag",
  "_fbp",
  "_fbc",
  "fr",
  "_pin_unauth",
  "_pinterest_ct_ua",
  "_hjSessionUser",
  "_hjSession",
  "_hjAbsoluteSessionInProgress",
  "_hjFirstSeen",
  "_hjIncludedInSessionSample",
  "ajs_anonymous_id",
  "ajs_user_id",
  "mp_",
  "amplitude_",
  "_clck",
  "_clsk",
  "CLID",
  "MR",
  "MUID",
  "SM",
  "IDE",
  "DSID",
  "NID",
  "__adroll",
  "__adroll_fpc",
  "__ar_v4",
  "personalization_id",
  "muc_ads",
  "ttclid",
  "_ttp",
  "sc_at",
  "li_sugr",
  "AnalyticsSyncHistory",
  "bcookie",
  "bscookie",
  "UserMatchHistory",
  "_tt_enable_cookie",
  "_ttp",
  "tt_ses",
  "tt_session",
  "_pin",
  "_pinterest_sess",
  "_pinterest_ct",
  "cto_bundle",
  "cto_bid",
  "cto_tld",
  "_lr_retry_request",
  "_lr_geo_request",
  "_gaexp",
  "_opt",
  "_ym_uid",
  "_ym_d",
  "ym_counter",
  "_hjid",
  "_hjSessionTooSample",
  "_hjUserAttributes",
  "_hjCachedUserAttributes",
  "_hjViewportId",
  "_hjQVAR",
  "ajs_group_id",
  "ajs_group_props",
  "ajs_traits",
  "_fsuid",
  "_fslc",
  "_fstc",
  "fsrace",
  "mp_timesince",
  "mp_event_timer",
  "_sp_id",
  "_sp_ses",
  "uv.ts",
  "uv.xid",
  "__qca",
  "_qzid",
  "_qzipi",
  "IR_gbd",
  "IR_PI",
  "_tac",
  "_tas",
  "_ta_notif_type",
  "trc_cookie_storage",
  "_tt_audio_session_id",
  "TAd5CJ1LDiS1",
  "IRF_36541",
  "s_vi",
  "s_getNewRepeat",
  "s_lv",
  "s_lv_s",
  "_vis_opt_s",
  "_vis_opt_test_cookie",
  "WME_UID",
  "aff_sub",
  "affiliate_id",
  "fbp",
  "fbclid",
  "gclid",
  "dclid",
  "ttclid",
  "twclid",
  "_uetvid",
  "uetvid",
  "msclkid"
];

export const HISTORY_LIMIT = 250;
