export const DEFAULTS = {
  enabled: true,
  mode: "reject", // reject | hide | accept
  blockCmpScripts: true,
  blockTrackers: true,
  stripTrackingCookies: true,
  whitelist: [],
  stats: {
    banners: 0,
    clicks: 0,
    hides: 0,
    trackers: 0,
    cookies: 0
  }
};

/** Domains whose cookies we purge aggressively (trackers only — not login sites). */
export const TRACKER_COOKIE_DOMAINS = [
  "doubleclick.net",
  "google-analytics.com",
  "googletagmanager.com",
  "googlesyndication.com",
  "googleadservices.com",
  "facebook.net",
  "scorecardresearch.com",
  "quantserve.com",
  "hotjar.com",
  "adsrvr.org",
  "adnxs.com",
  "criteo.com",
  "criteo.net",
  "rubiconproject.com",
  "pubmatic.com",
  "casalemedia.com",
  "demdex.net",
  "everesttech.net",
  "amazon-adsystem.com",
  "clarity.ms",
  "taboola.com",
  "outbrain.com",
  "segment.io",
  "mixpanel.com",
  "amplitude.com",
  "fullstory.com",
  "ads-twitter.com",
  "nr-data.net",
  "newrelic.com",
  "adsrvr.org",
  "liadm.com",
  "rlcdn.com",
  "bluekai.com",
  "exelator.com",
  "krxd.net",
  "mathtag.com",
  "moatads.com",
  "mookie1.com"
];

/** First-party cookie names that are almost always trackers. */
export const TRACKING_COOKIE_NAMES = [
  "_ga",
  "_gid",
  "_gat",
  "_gcl_au",
  "_gcl_aw",
  "_gcl_dc",
  "_gat_gtag",
  "_fbp",
  "_fbc",
  "fr",
  "_pin_unauth",
  "_pinterest_ct_ua",
  "_hjSessionUser",
  "_hjSession",
  "_hjAbsoluteSessionInProgress",
  "_hjFirstSeen",
  "_hjIncludedInSessionSample",
  "ajs_anonymous_id",
  "ajs_user_id",
  "mp_",
  "amplitude_",
  "_clck",
  "_clsk",
  "CLID",
  "MR",
  "MUID",
  "SM",
  "IDE",
  "DSID",
  "NID",
  "__adroll",
  "__adroll_fpc",
  "__ar_v4",
  "personalization_id",
  "muc_ads",
  "ttclid",
  "_ttp",
  "sc_at",
  "li_sugr",
  "AnalyticsSyncHistory",
  "bcookie",
  "bscookie",
  "UserMatchHistory"
];

export const HISTORY_LIMIT = 250;
